Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,11 +1,15 @@
 name: Lint
 on: [push]
 jobs:
-  eslint:
+  build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-  
-    - name: Validate package.json     
-    - name: Install dependencies
-      run: npm install
+      - uses: actions/checkout@v4
+      - name: Validate package.json
+        run: |
+          if ! jq empty package.json; then
+            echo "❌ Invalid package.json"
+            exit 1
+          fi
+      - name: Install dependencies
+        run: npm install
